version: "3.8"

services:
  redis:
    container_name: kvs
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/kvs:/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/app/.env
    ports:
      - 3000:3000
    volumes:
      - ./backend/app:/app
    depends_on:
      - redis

  nginx:
    container_name: proxy
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  kvs:

networks:
  default:
